version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  
      - "3000:3000" 
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py 